label:
  service: "${SERVICE:lares.account.interface}"
  profile: "${PROFILE:DEV}"
  version: "${VERSION:v0.0.1}"
  color: "${COLOR:local}"
  node: "${NODE}"
  language: "${LANGUAGE:en}"
trace:
  endpoint: http://localhost:14268/api/traces
log:
  type: zap
  level: debug
server:
  http:
    addr: 0.0.0.0:8001
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 5s
data:
  postgresql:
    source: ${POSTGRES_SOURCE}
    database: ${POSTGRES_DATABASE}
    dial_timeout: ${POSTGRES_DIAL_TIMEOUT}
  redis:
    addr: ${REDIS_ADDR}
    password: ${REDIS_PASSWORD}
    dial_timeout: ${REDIS_DIAL_TIMEOUT}
    read_timeout: ${REDIS_READ_TIMEOUT}
    write_timeout: ${REDIS_WRITE_TIMEOUT}
platform:
  apple:
    aud: {{APPLE_AUD}}
    iss: {{APPLE_ISS}}
    key_id: {{APPLE_KEY_ID}}
    team_id: {{APPLE_TEAM_ID}}
    client_id: {{APPLE_CLIENT_ID}}
    validator: {{APPLE_VALIDATOR}}
    secret: {{APPLE_SECRET}}
    redirect_uri: {{APPLE_REDIRECT_URI}}
    apple_sa_certs_url: {{APPLE_SACERTS_URL}}
    apple_auth_token_url: {{APPLE_AUTH_TOKEN_URL}}
  google:
    aud: {{GOOGLE_AUD}}
    iss1: {{GOOGLE_ISS1}}
    iss2: {{GOOGLE_ISS2}}
    json: {{GOOGLE_JSON}}
  facebook:
    app_id: {{FACEBOOK_APP_ID}}
    app_secret: {{FACEBOOK_APP_SECRET}}
