version: "2"
run:
  timeout: 5m
  tests: true
  concurrency: 4
  go: '1.21'

linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - bodyclose
    - gocritic
    - ineffassign
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: var-declaration
        severity: warning
      - name: exported
        severity: warning

formatters:
  enable:
    - gofmt
    - goimports

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  
  max-issues-per-linter: 50
  
  max-same-issues: 3