// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: account/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Trace         *Trace                 `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
	Server        *Server                `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Log           *Log                   `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	Platform      *Platform              `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Bootstrap) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Zone          uint32                 `protobuf:"varint,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Node          string                 `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	Language      string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Label) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Label) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Label) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Label) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Label) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *Label) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Label) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Trace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Health        string                 `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redis         *Data_Redis            `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	Postgresql    *Data_Postgresql       `protobuf:"bytes,2,opt,name=postgresql,proto3" json:"postgresql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetPostgresql() *Data_Postgresql {
	if x != nil {
		return x.Postgresql
	}
	return nil
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etcd          *Etcd                  `protobuf:"bytes,1,opt,name=etcd,proto3" json:"etcd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Registry) GetEtcd() *Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

type Etcd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etcd) Reset() {
	*x = Etcd{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etcd) ProtoMessage() {}

func (x *Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etcd.ProtoReflect.Descriptor instead.
func (*Etcd) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Etcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Etcd) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Etcd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenKey      string                 `protobuf:"bytes,1,opt,name=token_key,json=tokenKey,proto3" json:"token_key,omitempty"`
	SessionKey    string                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	PlatformKey   string                 `protobuf:"bytes,3,opt,name=platform_key,json=platformKey,proto3" json:"platform_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Secret) GetTokenKey() string {
	if x != nil {
		return x.TokenKey
	}
	return ""
}

func (x *Secret) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *Secret) GetPlatformKey() string {
	if x != nil {
		return x.PlatformKey
	}
	return ""
}

type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apple         *Apple                 `protobuf:"bytes,1,opt,name=apple,proto3" json:"apple,omitempty"`
	Google        *Google                `protobuf:"bytes,2,opt,name=google,proto3" json:"google,omitempty"`
	Facebook      *Facebook              `protobuf:"bytes,3,opt,name=facebook,proto3" json:"facebook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Platform) GetApple() *Apple {
	if x != nil {
		return x.Apple
	}
	return nil
}

func (x *Platform) GetGoogle() *Google {
	if x != nil {
		return x.Google
	}
	return nil
}

func (x *Platform) GetFacebook() *Facebook {
	if x != nil {
		return x.Facebook
	}
	return nil
}

type Apple struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AudApp            string                 `protobuf:"bytes,1,opt,name=aud_app,json=audApp,proto3" json:"aud_app,omitempty"`
	AudWeb            string                 `protobuf:"bytes,2,opt,name=aud_web,json=audWeb,proto3" json:"aud_web,omitempty"`
	Iss               string                 `protobuf:"bytes,3,opt,name=iss,proto3" json:"iss,omitempty"`
	KeyId             string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,5,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ClientId          string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Validator         string                 `protobuf:"bytes,7,opt,name=validator,proto3" json:"validator,omitempty"`
	Secret            string                 `protobuf:"bytes,8,opt,name=secret,proto3" json:"secret,omitempty"`
	RedirectUri       string                 `protobuf:"bytes,9,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	AppleSaCertsUrl   string                 `protobuf:"bytes,10,opt,name=apple_sa_certs_url,json=appleSaCertsUrl,proto3" json:"apple_sa_certs_url,omitempty"`
	AppleAuthTokenUrl string                 `protobuf:"bytes,11,opt,name=apple_auth_token_url,json=appleAuthTokenUrl,proto3" json:"apple_auth_token_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Apple) Reset() {
	*x = Apple{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apple) ProtoMessage() {}

func (x *Apple) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apple.ProtoReflect.Descriptor instead.
func (*Apple) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Apple) GetAudApp() string {
	if x != nil {
		return x.AudApp
	}
	return ""
}

func (x *Apple) GetAudWeb() string {
	if x != nil {
		return x.AudWeb
	}
	return ""
}

func (x *Apple) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *Apple) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Apple) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Apple) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Apple) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *Apple) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Apple) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *Apple) GetAppleSaCertsUrl() string {
	if x != nil {
		return x.AppleSaCertsUrl
	}
	return ""
}

func (x *Apple) GetAppleAuthTokenUrl() string {
	if x != nil {
		return x.AppleAuthTokenUrl
	}
	return ""
}

type Google struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aud           string                 `protobuf:"bytes,1,opt,name=aud,proto3" json:"aud,omitempty"`
	Iss1          string                 `protobuf:"bytes,2,opt,name=iss1,proto3" json:"iss1,omitempty"`
	Iss2          string                 `protobuf:"bytes,3,opt,name=iss2,proto3" json:"iss2,omitempty"`
	Json          string                 `protobuf:"bytes,4,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Google) Reset() {
	*x = Google{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Google) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Google) ProtoMessage() {}

func (x *Google) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Google.ProtoReflect.Descriptor instead.
func (*Google) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Google) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *Google) GetIss1() string {
	if x != nil {
		return x.Iss1
	}
	return ""
}

func (x *Google) GetIss2() string {
	if x != nil {
		return x.Iss2
	}
	return ""
}

func (x *Google) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type Facebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppSecret     string                 `protobuf:"bytes,2,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facebook) Reset() {
	*x = Facebook{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facebook) ProtoMessage() {}

func (x *Facebook) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facebook.ProtoReflect.Descriptor instead.
func (*Facebook) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{12}
}

func (x *Facebook) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Facebook) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Postgresql struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Postgresql) Reset() {
	*x = Data_Postgresql{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Postgresql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Postgresql) ProtoMessage() {}

func (x *Data_Postgresql) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Postgresql.ProtoReflect.Descriptor instead.
func (*Data_Postgresql) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Data_Postgresql) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Postgresql) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Data_Postgresql) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Cluster       bool                   `protobuf:"varint,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,4,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,5,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,6,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_account_internal_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_account_internal_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_account_internal_conf_conf_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetCluster() bool {
	if x != nil {
		return x.Cluster
	}
	return false
}

func (x *Data_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

var File_account_internal_conf_conf_proto protoreflect.FileDescriptor

const file_account_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	" account/internal/conf/conf.proto\x12\x15account.internal.conf\x1a\x1egoogle/protobuf/duration.proto\"\xc6\x02\n" +
	"\tBootstrap\x122\n" +
	"\x05label\x18\x01 \x01(\v2\x1c.account.internal.conf.LabelR\x05label\x122\n" +
	"\x05trace\x18\x02 \x01(\v2\x1c.account.internal.conf.TraceR\x05trace\x125\n" +
	"\x06server\x18\x03 \x01(\v2\x1d.account.internal.conf.ServerR\x06server\x12/\n" +
	"\x04data\x18\x04 \x01(\v2\x1b.account.internal.conf.DataR\x04data\x12,\n" +
	"\x03log\x18\x05 \x01(\v2\x1a.account.internal.conf.LogR\x03log\x12;\n" +
	"\bplatform\x18\x06 \x01(\v2\x1f.account.internal.conf.PlatformR\bplatform\"\xaf\x01\n" +
	"\x05Label\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\rR\x04zone\x12\x12\n" +
	"\x04node\x18\x06 \x01(\tR\x04node\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\"#\n" +
	"\x05Trace\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"/\n" +
	"\x03Log\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\xe6\x02\n" +
	"\x06Server\x126\n" +
	"\x04http\x18\x01 \x01(\v2\".account.internal.conf.Server.HTTPR\x04http\x126\n" +
	"\x04grpc\x18\x02 \x01(\v2\".account.internal.conf.Server.GRPCR\x04grpc\x12\x16\n" +
	"\x06health\x18\x03 \x01(\tR\x06health\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x97\x04\n" +
	"\x04Data\x127\n" +
	"\x05redis\x18\x01 \x01(\v2!.account.internal.conf.Data.RedisR\x05redis\x12F\n" +
	"\n" +
	"postgresql\x18\x02 \x01(\v2&.account.internal.conf.Data.PostgresqlR\n" +
	"postgresql\x1a~\n" +
	"\n" +
	"Postgresql\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12<\n" +
	"\fdial_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x1a\x8d\x02\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\acluster\x18\x03 \x01(\bR\acluster\x12<\n" +
	"\fdial_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12<\n" +
	"\fread_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\";\n" +
	"\bRegistry\x12/\n" +
	"\x04etcd\x18\x01 \x01(\v2\x1b.account.internal.conf.EtcdR\x04etcd\"\\\n" +
	"\x04Etcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"i\n" +
	"\x06Secret\x12\x1b\n" +
	"\ttoken_key\x18\x01 \x01(\tR\btokenKey\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\tR\n" +
	"sessionKey\x12!\n" +
	"\fplatform_key\x18\x03 \x01(\tR\vplatformKey\"\xb2\x01\n" +
	"\bPlatform\x122\n" +
	"\x05apple\x18\x01 \x01(\v2\x1c.account.internal.conf.AppleR\x05apple\x125\n" +
	"\x06google\x18\x02 \x01(\v2\x1d.account.internal.conf.GoogleR\x06google\x12;\n" +
	"\bfacebook\x18\x03 \x01(\v2\x1f.account.internal.conf.FacebookR\bfacebook\"\xcf\x02\n" +
	"\x05Apple\x12\x17\n" +
	"\aaud_app\x18\x01 \x01(\tR\x06audApp\x12\x17\n" +
	"\aaud_web\x18\x02 \x01(\tR\x06audWeb\x12\x10\n" +
	"\x03iss\x18\x03 \x01(\tR\x03iss\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x17\n" +
	"\ateam_id\x18\x05 \x01(\tR\x06teamId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x1c\n" +
	"\tvalidator\x18\a \x01(\tR\tvalidator\x12\x16\n" +
	"\x06secret\x18\b \x01(\tR\x06secret\x12!\n" +
	"\fredirect_uri\x18\t \x01(\tR\vredirectUri\x12+\n" +
	"\x12apple_sa_certs_url\x18\n" +
	" \x01(\tR\x0fappleSaCertsUrl\x12/\n" +
	"\x14apple_auth_token_url\x18\v \x01(\tR\x11appleAuthTokenUrl\"V\n" +
	"\x06Google\x12\x10\n" +
	"\x03aud\x18\x01 \x01(\tR\x03aud\x12\x12\n" +
	"\x04iss1\x18\x02 \x01(\tR\x04iss1\x12\x12\n" +
	"\x04iss2\x18\x03 \x01(\tR\x04iss2\x12\x12\n" +
	"\x04json\x18\x04 \x01(\tR\x04json\"@\n" +
	"\bFacebook\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"app_secret\x18\x02 \x01(\tR\tappSecretB Z\x1eapp/account/internal/conf;confb\x06proto3"

var (
	file_account_internal_conf_conf_proto_rawDescOnce sync.Once
	file_account_internal_conf_conf_proto_rawDescData []byte
)

func file_account_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_account_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_account_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_internal_conf_conf_proto_rawDesc), len(file_account_internal_conf_conf_proto_rawDesc)))
	})
	return file_account_internal_conf_conf_proto_rawDescData
}

var file_account_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_account_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: account.internal.conf.Bootstrap
	(*Label)(nil),               // 1: account.internal.conf.Label
	(*Trace)(nil),               // 2: account.internal.conf.Trace
	(*Log)(nil),                 // 3: account.internal.conf.Log
	(*Server)(nil),              // 4: account.internal.conf.Server
	(*Data)(nil),                // 5: account.internal.conf.Data
	(*Registry)(nil),            // 6: account.internal.conf.Registry
	(*Etcd)(nil),                // 7: account.internal.conf.Etcd
	(*Secret)(nil),              // 8: account.internal.conf.Secret
	(*Platform)(nil),            // 9: account.internal.conf.Platform
	(*Apple)(nil),               // 10: account.internal.conf.Apple
	(*Google)(nil),              // 11: account.internal.conf.Google
	(*Facebook)(nil),            // 12: account.internal.conf.Facebook
	(*Server_HTTP)(nil),         // 13: account.internal.conf.Server.HTTP
	(*Server_GRPC)(nil),         // 14: account.internal.conf.Server.GRPC
	(*Data_Postgresql)(nil),     // 15: account.internal.conf.Data.Postgresql
	(*Data_Redis)(nil),          // 16: account.internal.conf.Data.Redis
	(*durationpb.Duration)(nil), // 17: google.protobuf.Duration
}
var file_account_internal_conf_conf_proto_depIdxs = []int32{
	1,  // 0: account.internal.conf.Bootstrap.label:type_name -> account.internal.conf.Label
	2,  // 1: account.internal.conf.Bootstrap.trace:type_name -> account.internal.conf.Trace
	4,  // 2: account.internal.conf.Bootstrap.server:type_name -> account.internal.conf.Server
	5,  // 3: account.internal.conf.Bootstrap.data:type_name -> account.internal.conf.Data
	3,  // 4: account.internal.conf.Bootstrap.log:type_name -> account.internal.conf.Log
	9,  // 5: account.internal.conf.Bootstrap.platform:type_name -> account.internal.conf.Platform
	13, // 6: account.internal.conf.Server.http:type_name -> account.internal.conf.Server.HTTP
	14, // 7: account.internal.conf.Server.grpc:type_name -> account.internal.conf.Server.GRPC
	16, // 8: account.internal.conf.Data.redis:type_name -> account.internal.conf.Data.Redis
	15, // 9: account.internal.conf.Data.postgresql:type_name -> account.internal.conf.Data.Postgresql
	7,  // 10: account.internal.conf.Registry.etcd:type_name -> account.internal.conf.Etcd
	10, // 11: account.internal.conf.Platform.apple:type_name -> account.internal.conf.Apple
	11, // 12: account.internal.conf.Platform.google:type_name -> account.internal.conf.Google
	12, // 13: account.internal.conf.Platform.facebook:type_name -> account.internal.conf.Facebook
	17, // 14: account.internal.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	17, // 15: account.internal.conf.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	17, // 16: account.internal.conf.Data.Postgresql.dial_timeout:type_name -> google.protobuf.Duration
	17, // 17: account.internal.conf.Data.Redis.dial_timeout:type_name -> google.protobuf.Duration
	17, // 18: account.internal.conf.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	17, // 19: account.internal.conf.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_account_internal_conf_conf_proto_init() }
func file_account_internal_conf_conf_proto_init() {
	if File_account_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_internal_conf_conf_proto_rawDesc), len(file_account_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_account_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_account_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_account_internal_conf_conf_proto = out.File
	file_account_internal_conf_conf_proto_goTypes = nil
	file_account_internal_conf_conf_proto_depIdxs = nil
}
