label:
  service: "${SERVICE:rec-account.notice.interface}"
  profile: "${PROFILE:DEV}"
  version: "${VERSION:v0.0.1}"
  color: "${COLOR:local}"
  node: "${NODE}"
  language: "${LANGUAGE:en}"
trace:
  endpoint: http://localhost:14268/api/traces
log:
  type: zap
  level: debug
server:
  http:
    addr: 0.0.0.0:8002
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 5s
data:
  postgres:
    driver: postgres
    source: host=localhost user={{PG_USER}} password={{PG_PASSWORD}} dbname=rec_account port=5432 TimeZone=Asia/Singapore
    max_idle_conns: 20
    max_open_conns: 200
  redis:
    addr: localhost:6379
    password: {{REDIS_PASSWORD}}
    read_timeout: 0.5s
    write_timeout: 0.5s
platform:
  apple:
    aud: {{APPLE_AUD}}
    iss: {{APPLE_ISS}}
  google:
    aud: {{GOOGLE_AUD}}
    iss1: {{GOOGLE_ISS1}}
    iss2: {{GOOGLE_ISS2}}
    json: {{GOOGLE_JSON}}
  facebook:
    app_id: {{FACEBOOK_APP_ID}}
    app_secret: {{FACEBOOK_APP_SECRET}}
